import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const prod = (process.argv[2] === "production");
const vaultPluginDir = "D:\\Obsidian Vault\\Obsidian Vault\\.obsidian\\plugins\\obsidian-smart-dashboard";

console.log("Building Smart Dashboard with esbuild.buildSync...");

try {
	esbuild.buildSync({
		banner: {
			js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/',
		},
		entryPoints: ["main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr"
		],
		format: "cjs",
		target: "es2018",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: "main.js",
		write: true
	});
	console.log("Build main.js success.");

	if (fs.existsSync(vaultPluginDir)) {
		fs.copyFileSync("main.js", path.join(vaultPluginDir, "main.js"));
		if (fs.existsSync("manifest.json")) fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
		if (fs.existsSync("styles.css")) fs.copyFileSync("styles.css", path.join(vaultPluginDir, "styles.css"));
		console.log("Successfully copied build outputs directly into Obsidian Vault plugin directory!");
	}
} catch (e) {
	console.error("Build failed:", e);
}

process.exit(0);
